version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_CONFIG=production
      - SECRET_KEY=secret_key
    command: >
      bash -c "python app.py" 